name: Test

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}

    strategy:
      matrix:
        os:
          - ubuntu
          - macos

        ruby:
          - '3.2'
          - '3.3'

        experimental: [false]

        include:
          - os: ubuntu
            ruby: truffleruby
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: true

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Setup database
        run: RACK_ENV='test' bundle exec ruby db/setup.rb

      - name: Run tests
        run: RACK_ENV='test' bundle exec rspec
